name = "LeanSerde"
version = "0.1.0"
defaultTargets = ["leanserde"]
testDriver = "tests"

[[lean_lib]]
name = "LeanSerde"

[[lean_lib]]
name = "Tests"

[[lean_exe]]
name = "leanserde"
root = "Main"

[[lean_exe]]
name = "tests"
root = "Tests.TestRunner"