name = "LeanSerial"
version = "0.1.0"
defaultTargets = ["leanserial"]
testDriver = "tests"

[[lean_lib]]
name = "LeanSerial"

[[lean_lib]]
name = "Tests"

[[lean_lib]]
name = "Proofs"

[[lean_exe]]
name = "leanserial"
root = "Main"

[[lean_exe]]
name = "tests"
root = "Tests.TestRunner"